---
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "gary1.fullname" . }}-testpod"
  labels:
    app.kubernetes.io/name: {{ include "gary1.name" . }}
    helm.sh/chart: {{ include "gary1.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan-conf-test", "interfaceRequest": "macvlan-conf" }
    ]'
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    args: ['{{ include "gary1.fullname" . }}:{{ .Values.service.port }}']
    image: dougbtv/centos-network
    ports:
    - containerPort: 80

